# Generated by Django 4.1.3 on 2023-01-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0002_class_total_hours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campus_attendance',
            unique_together=set(),
        ),
    ]
