# Generated by Django 4.1.3 on 2022-11-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0002_alter_attendance__class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time_in',
            field=models.TimeField(),
        ),
    ]
