# Generated by Django 4.1.3 on 2022-11-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0002_class_course_department_guardian_subject_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=2)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='school_year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClassSchedule',
        ),
        migrations.AddField(
            model_name='class_schedule',
            name='_class',
            field=models.ForeignKey(db_column='class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='e_attendance.class'),
        ),
    ]
