# Generated by Django 4.1.3 on 2022-11-09 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0003_class_schedule_class_school_year_class_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_schedule',
            name='_class',
            field=models.ForeignKey(db_column='class_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='e_attendance.class'),
        ),
    ]
