# Generated by Django 4.1.3 on 2022-11-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0003_alter_attendance_time_in'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('_class', 'student', 'date')},
        ),
    ]
