# Generated by Django 4.1.3 on 2023-02-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0003_alter_campus_attendance_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
