# Generated by Django 4.1.3 on 2022-12-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0004_employee_attendance_delete_teacher_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_attendance',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
