# Generated by Django 4.1.3 on 2022-11-18 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0005_remove_class_students_class_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='_class',
            new_name='classs',
        ),
        migrations.RemoveField(
            model_name='class_student',
            name='_class',
        ),
        migrations.AddField(
            model_name='class_student',
            name='classs',
            field=models.ForeignKey(db_column='class_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='e_attendance.class'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('classs', 'student', 'date')},
        ),
    ]
