# Generated by Django 4.1.3 on 2023-02-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0006_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='school_year',
            field=models.CharField(max_length=10),
        ),
    ]
