# Generated by Django 4.1.3 on 2022-11-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0006_user_user_type_alter_instructor_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'guardian'), (4, 'admin')], null=True),
        ),
    ]
