# Generated by Django 4.1.3 on 2022-11-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0006_rename__class_attendance_classs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='classs',
            new_name='cls',
        ),
        migrations.RenameField(
            model_name='class_student',
            old_name='classs',
            new_name='cls',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('cls', 'student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='class_student',
            unique_together={('cls', 'student')},
        ),
    ]
