# Generated by Django 4.1.3 on 2022-11-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0008_alter_attendance_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_guardian',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='e_attendance.guardian'),
        ),
        migrations.AlterField(
            model_name='student_guardian',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardians', to='e_attendance.student'),
        ),
    ]
