# Generated by Django 4.1.3 on 2022-12-18 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0008_alter_class_student_cls_alter_class_student_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_schedule',
            name='cls',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='e_attendance.class'),
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='cls',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='e_attendance.class'),
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
