# Generated by Django 4.1.3 on 2022-11-13 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_attendance', '0011_rename_attendansu_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='time',
            new_name='time_in',
        ),
    ]
